FROM google/cloud-sdk:alpine@sha256:80eb077f2357fa236e5c709fc9281bb12848c06b2edac72209c69f12f342bbb1
MAINTAINER Vic Iglesias <viglesias@google.com>

COPY run-builder.sh /bin
CMD ["bash", "-xe", "/bin/run-builder.sh"]